Repository gisce/poweremail, pull requests merged in 2020-01, with the labels that each got.

#67 Add traceback to error message
  poweremail_mailbox.py
Labels: deployed, enhancement

#72 Validate body message before sending
  poweremail_mailbox.py
Labels: To Merge, enhancement

#73 FIX: Validate body message before sending
  poweremail_mailbox.py
Labels: To Merge, bug

#74 Send empty string intead of "False" in case html is empty
  poweremail_mailbox.py
Labels: To Merge, bug

#75 Mover de calcular cuenta de origen logica en un metodo para poder sobreescrivirlo
  poweremail_template.py
  tests/__init__.py
Labels: To Merge, enhancement
