Repository gisce/poweremail, pull requests merged in 2022-09, with the labels that each got.

#92 Nuevas vistas para plantillas con formato basico del poweremail
  __terp__.py
  poweremail_template_view.xml
  wizard/__init__.py
  wizard/wizard_generate_test_email.py
  wizard/wizard_generate_test_email.xml
Labels: To Merge, deployed

#94 Añadir la prioridad a la visa de las plantillas de power email
  poweremail_template_view.xml
Labels: To Merge

#95 Create and write date on mailbox
  poweremail_mailbox.py
Labels: enhancement
