Repository gisce/poweremail, pull requests merged in 2023-06, with the labels that each got.

#86 NEW Create the generic model to list generated mails
  __init__.py
  __terp__.py
  wizard/__init__.py
  wizard/wizard_emails_generats.py
  wizard/wizard_emails_generats.xml
Labels: enhancement, deployed, wip

#108 Fix missing comma in update __terp__
  __terp__.py
Labels: bug, To Merge

#109 Add templates attachements only works with lang on context
  poweremail_send_wizard.py
Labels: bug, To Merge, deployed
