Repository gisce/poweremail, pull requests merged in 2023-07, with the labels that each got.

#111 Arreglar el asistente para generar correos de prueba
  migrations/5.0.23.9.0/post-0001_fix_generate_test_email.py
  wizard/wizard_generate_test_email.xml
Labels: bug, deployed

#112 Mostrar en el mailbox la plantilla del poweremail a la que corresponde
  migrations/5.0.23.9.0/post-0002_add_template_id_mailbox_view.py
  poweremail_mailbox_view.xml
  poweremail_send_wizard.py
  poweremail_template.py
  wizard/wizard_generate_test_email.py
Labels: deployed

#110 Mostrar todos los emails
  i18n/ca_ES.po
  i18n/es_ES.po
  i18n/poweremail.pot
  migrations/5.0.23.6.0/post-0002_update_to_see_all_emails.py
  poweremail_mailbox_view.xml
Labels: enhancement

#113 Nuevo método generate mail sync
  poweremail_template.py
Labels: enhancement
