Repository gisce/poweremail, pull requests merged in 2024-08, with the labels that each got.

#163 Poder importar ficheros .mako en el cuerpo de la plantilla de Poweremail y nuevas variables en el scope de la plantilla
  __init__.py
  poweremail_template.py
  utils.py
Labels: to be merged, deployed, improvement, deployed PRE

#166 Allow env variables in template preview
  migrations/5.0.24.9.0/post-0002_update_preview_email_view.py
  poweremail_template.py
  wizard/wizard_poweremail_preview.py
  wizard/wizard_poweremail_preview.xml
Labels: to be merged, improvement

#167 No se renderizaba el contenido del email si no se encontraba idioma
  migrations/5.0.24.9.0/post-0003_update_preview_email_view.py
  poweremail_template.py
  wizard/wizard_poweremail_preview.py
  wizard/wizard_poweremail_preview.xml
Labels: bug, to be merged, deployed, deployed PRE

#169 El idioma con prioridad debe ser el que viene en la plantilla y no el que hay en el contexto
  poweremail_template.py
Labels: bug, to be merged, deployed
