Repository gisce/poweremail, pull requests merged in 2024-07, with the labels that each got.

#162 Renderizar error en HTML cuando falla la previsualización del cuerpo del mail desde el asistente de previsualizar correo
  wizard/wizard_poweremail_preview.py
Labels: to be merged, improvement

#165 Script de migración para la pull request #164
  migrations/5.0.24.9.0/post-0001_update_preview_email_view.py
Labels: deployed PRE

#149 Mostrar el contenido del correo renderizado en HTML
  migrations/5.0.24.5.0/post-0001_update_poweremail_mailbox_view.py
  poweremail_mailbox_view.xml
Labels: enhancement, to be merged, deployed, deployed PRE
