Repository gisce/poweremail, pull requests merged in 2025-04, with the labels that each got.

#161 Add indicators to poweremail.core_accounts form
  migrations/5.0.24.9.0/post-0001_load_indicators.py
  poweremail_core_view.xml
Labels: enhancement, to be merged

#182 Move the buttons and the fields that enables the send email wizard to a new tab
  i18n/ca_ES.po
  i18n/es_ES.po
  i18n/poweremail.pot
  migrations/5.0.25.5.0/post-0001_update_translations_and_template_view.py
  poweremail_template_view.xml
Labels: to be merged, improvement, UX

#190 Fix poweremail demo data
  poweremail_demo.xml
Labels: bug, to be merged

#189 Relate generated email to resource when created from preview wizard
  wizard/wizard_poweremail_preview.py
Labels: to be merged, improvement

#186 Añadir los estilos inline en el previsualizador de las plantillas
  wizard/wizard_poweremail_preview.py
Labels: to be merged, improvement

#185 Refactor set attachments functions
  poweremail_template.py
Labels: to be merged, improvement

#191 Fix demo data
  emails/default_template_poweremail/index.mako
  poweremail_demo.xml
Labels: bug, to be merged
