Repository gisce/poweremail, pull requests merged in 2025-02, with the labels that each got.

#175 Allow manual execute from owner
  .github/workflows/run_tests.yml
Labels: to be merged, CI

#176 Use pr ref
  .github/workflows/run_tests.yml
Labels: to be merged, CI

#155 Add template body text optional inliner
  migrations/5.0.24.5.0/post-0002_activar_inliner.py
  migrations/5.0.24.5.0/pre-0001_instalar_premailer.py
  poweremail_send_wizard.py
  poweremail_template.py
  poweremail_template_view.xml
  requirements.txt
  tests/test_poweremail_mailbox.py
  tests/test_poweremail_templates.py
Labels: to be merged, improvement

#178 Allow custom senders and move Sender construction in separated functions to easy inheritance
  poweremail_core.py
Labels: to be merged
